//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugRequest
    {
        public int DrugReqID { get; set; }
        public System.DateTime DrugReqDate { get; set; }
        public string DrugReqStatus { get; set; }
        public Nullable<int> PhysicianID { get; set; }
    
        public virtual Physician Physician { get; set; }
    }
}
