//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Physician
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Physician()
        {
            this.Appointments = new HashSet<Appointment>();
            this.DrugRequests = new HashSet<DrugRequest>();
        }
    
        public int PhysicianID { get; set; }
        public string PhysicianName { get; set; }
        public System.DateTime PhysicianDOB { get; set; }
        public string PhysicianGender { get; set; }
        public string PhysicianSpecialization { get; set; }
        public decimal PhysicianContact { get; set; }
        public string PhysicianEmailID { get; set; }
        public string PhysicianAddress { get; set; }
        public string Note { get; set; }
        public Nullable<int> UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugRequest> DrugRequests { get; set; }
        public virtual User User { get; set; }
    }
}
